### ISSUE TITLE
 [] operator not supported

### ISSUE THREAD

**Issue by lottaar** [modxcms/Archivist#8]
Hi,

I've upgraded my site to MODX 2.5.7 and moved it to a new web server with PHP 7.1. Now I get the below error when using Archivist 1.2.4-pl. Is it due to incompatibility with PHP 7 and is there a quick way of solving it?

Thanks!

`Fatal error: Uncaught Error: [] operator not supported for strings in /var/www/vhosts/mydomain.com/httpdocs/core/cache/includes/elements/modsnippet/2.include.cache.php:60 Stack trace: #0 /var/www/vhosts/mydomain.com/httpdocs/core/model/modx/modscript.class.php(70): include() #1 /var/www/vhosts/mydomain.com/httpdocs/core/model/modx/modparser.class.php(521): modScript->process() #2 /var/www/vhosts/mydomain.com/httpdocs/core/model/modx/modparser.class.php(250): modParser->processTag(Array, true) #3 /var/www/vhosts/mydomain.com/httpdocs/core/model/modx/modresponse.class.php(69): modParser->processElementTags('', '<!DOCTYPE html ...', true, false, '[[', ']]', Array, 9) #4 /var/www/vhosts/mydomain.com/httpdocs/core/model/modx/modrequest.class.php(137): modResponse->outputContent(Array) #5 /var/www/vhosts/mydomain.com/httpdocs/core/model/modx/modx.class.php(1146): modRequest->prepareResponse() #6 /var/www/vhosts/mydomain.com/httpdocs/core/cache/includes/elements/modplugin/1.include.cache.php(76): modX->sendForwar in /var/www/vhosts/mydomain.com/httpdocs/core/cache/includes/elements/modsnippet/2.include.cache.php on line 60`

**Comment by Mark-H** [comment]
Suspect [this line](https://github.com/modxcms/Archivist/blob/develop/core/components/archivist/elements/snippets/snippet.getarchives.php#L60) caused by either an invalid &where property, or no &where property. Code should check better if it's an array or not. 

Perhaps this can be used as workaround ````&where=`[]` ```` to pass it an empty json array.

**Comment by jonleverrier** [comment]
had the same issue.

adding `&where=`[]` ` worked for me. I'm running PHP7.1.1

thanks @Mark-H !

**Comment by lottaar** [comment]
Indeed, adding &where=`[]` to  my [[!getArchives]] call did the trick for me as well.

Thanks guys!
